### ISSUE TITLE
Jump to header in daily note

### ISSUE THREAD

**Issue by HEmile** [ryanjamurphy/lumberjack-obsidian#1]
Hi, I really like this idea and have been looking for something like this. My daily note however is somewhat structured in certain categories (like news, journal, pictures...), and I'd usually want to log something under one of those headings (ideally at the end, just before the next heading). Is it possible to provide an argument such that you can jump to the end of such a given heading?

**Comment by ryanjamurphy** [comment]
Yeah, good point! 

The algorithm to determine the end of such a section is a bit tricky. Do you think this would be sufficient instead?

Pseudocode:
```
settings.insertPosition: "above" || "below";
settings.targetHeading "## Some Heading";

- Insert new item (settings.insertPosition) settings.targetHeading
```

I.e., if the user has a `## Log` section, then a `## News` heading, you could make it prepend above News, or append just below Log.

**Comment by HEmile** [comment]
For me it's fine, actually! But yeah, I agree it's not perfect. I actually wrote something related a couple days ago: https://github.com/SkepticMystic/graph-analysis/blob/2067987f47b6b5aec57ab646416c8d9b32fbc6ae/src/MyGraph.ts#L173

This will look for the current `heading` when the next heading with the same or lower level appears. Since the heading cache in Obsidian is sorted on appearence, this is fine :)
