### ISSUE TITLE
Can't create a new note

### ISSUE THREAD

**Issue by mtalexan** [ryanjamurphy/lumberjack-obsidian#11]
I invoked the `obsidian://timber` from a shortcut and it always reports the file can't be created. It asks if the folder exists.

I have my settings configured to create the file in my `Personal/Misc` folder, which already includes some files.

Settings:
![Screenshot_20220127-213855_Obsidian](https://user-images.githubusercontent.com/7081950/151493798-86c03a4a-ef5c-4368-908f-158a85cc1268.png)

Folders:
![Screenshot_20220127-213918_Obsidian](https://user-images.githubusercontent.com/7081950/151493829-ab8df378-d8f7-492d-b4a6-09700ce357e9.png)

**Comment by ryanjamurphy** [comment]
I wonder if it's case-sensitive: it looks like your "Misc" folder is actually `MIsc`. Mind correcting that and trying again? (I'm actually not sure if it should be case-insensitive or not... something to think about)

**Comment by mtalexan** [comment]
Well I'm an idiot. I looked at that a dozen times and never noticed that capitalization issue in the folder name at all. That was absolutely it, if if seen it before it would have been obvious to me.
