### ISSUE TITLE
New release has the old main.js

### ISSUE THREAD

**Issue by RobertoGoAm** [ryanjamurphy/lumberjack-obsidian#14]
@ryanjamurphy it seems the attached `main.js` in the release is the old one, so the update makes no effect 😅. Can you fix that up? Don't think I can do anything on my end.

**Comment by ryanjamurphy** [comment]
Odd. Swapped it out — try now? Sorry.

**Comment by RobertoGoAm** [comment]
Fixed! Thank you very much!
