### ISSUE TITLE
IOS Background reload

### ISSUE THREAD

**Issue by jasoncym** [ryanjamurphy/lumberjack-obsidian#16]
Thanks for telling me how to use this plugin in a previous email, I use it very often now and find it very useful. However, on IOS, there is a situation when it takes up a lot of memory (usually after opening the camera to take a picture), opening Obsidian with the log shortcut requires a reload, and direct input is not accessible, i.e. there is actually no command to run this log, only the main Obsidian program is opened.

In the same case, I found no problem using the Memos plugin, and even with such a reload, direct input can still be accessed, even if it is slightly slower.

Can you please tell me if this issue can be handled? I'm not quite sure if this is within the scope of what this plugin can handle, or if there is another solution? Thank you!

**Comment by ryanjamurphy** [comment]
Can you take a screen recording of this behaviour? It's probably just Obsidian's startup time that's getting in the way, and I'm afraid there's not much I can do about that.

**Comment by jasoncym** [comment]
Thank you for your reply. This situation may happen several times a day. It is not stable.
https://user-images.githubusercontent.com/53342853/222481829-34582e88-f04b-425a-bc9a-4fe70112bf15.mp4

**Comment by ryanjamurphy** [comment]
Ah, unfortunately, that is the app itself. If Obsidian gets backgrounded, your vault needs to be re-launched when the app is activated again. That doesn't have anything to do with Lumberjack and I'm afraid there's nothing I can do about it.

On Android, you may be able to get a better experience by preventing the app from sleeping/keeping it active in the background: <https://www.androidpolice.com/prevent-apps-from-sleeping-in-the-background-on-android/> (I can't comment on this, though, as I don't use Android.)

**Comment by jasoncym** [comment]
Ok, thank you. I'm preparing to study whether drafts can solve this problem. Do you have such a situation?

**Comment by ryanjamurphy** [comment]
Drafts is more an alternative to Lumberjack than anything else. I didn't think Drafts was on Android, though...
