### ISSUE TITLE
Ability to specify time format

### ISSUE THREAD

**Issue by WychWitch** [ryanjamurphy/lumberjack-obsidian#2]
Hello! I love this plugin so much, it will make me so much more productive! However I use a different format for logs (1:40pm not 13:40) and I would love to be able to specify that over the built in method. Thank you in advance!

**Comment by ryanjamurphy** [comment]
Good idea; should be easy to implement. I'll let you know when I get the chance!

**Comment by WychWitch** [comment]
Thank you!! I'll be happy to have constant times ^^

**Comment by WychWitch** [comment]
YESS it works perfect;y!! Thank you so much for this update!
