### ISSUE TITLE
App freezes when using log on iOS

### ISSUE THREAD

**Issue by cyrulnik** [ryanjamurphy/lumberjack-obsidian#4]
For me -- running the log shortcut on iOS launches Obsidian but then it freezes and needs to be force-quit.

**Comment by ryanjamurphy** [comment]
Very odd. Sorry for the trouble. 

I think I've got it, actually. Do you have sections (e.g., any headings) in your daily note?

**Comment by cyrulnik** [comment]
I spent some more time playing around with this. Here is what I found for my setup:

If the section where the log entry is supposed to go is at the BOTTOM of the DNP, then it seems work fine on both iOS and Desktop. But if the section is at the top of the DNP and there are other sections beneath it, then triggering the log command freezes Obsidian completely on both iOS and Desktop. Not sure if this is helpful -- but thought I would post just in case.

**Comment by cyrulnik** [comment]
ok. here is a screenshot where it works fine

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/69698482/138391424-ce7d1c09-16ef-4de6-8751-88aa275623e7.png">

And here is a screenshot where, if I trigger log from the command palette, it causes the Obsidian window to freeze and need to be force-quit:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/69698482/138391468-5b90944b-37fb-4eab-813b-ad323538a664.png">

It's very odd. It seems like it has something to do with whether there is no text under the designated heading -- but it's not 100% explained by that.
