### ISSUE TITLE
Could Prefix for logging understand {{time:HH:mm}}?

### ISSUE THREAD

**Issue by kontiainen** [ryanjamurphy/lumberjack-obsidian#5]
Tried to use

({{time:HH:mm}})

as Prefix for logging, but it does not seem to work. 

Is there a way to get this working?

**Comment by ryanjamurphy** [comment]
What are you trying to achieve? There is already a built in timestamp, see the plugin preferences!

**Comment by kontiainen** [comment]
I've used to have a prefix like 
(20:54) 
for each Journal entry.

**Comment by z2k-gwp** [comment]
@kontiainen - I thought I'd help @ryanjamurphy out by mentioning that you can use regex101.com to do testing of format strings regex matching. Unfortunately, in your case, everything works out so it is not obvious what is failing.
![dateFormatTesting](https://user-images.githubusercontent.com/84196203/141431187-96722aa2-23be-450c-8030-3e1beed4ed4b.png)

**Comment by ryanjamurphy** [comment]
Yeah, this is already possible. Use square brackets in the timestamp field to escape text you want to include as-is. For example, `[(]HH:mm[)]` will output the timestamp `(12:32)`. You can use this in combination with the prefix field, too. A prefix of `- [ ] ` and a timestamp `[(]HH:mm[)]` will create a line starting with...
```
- [ ] (12:33) 
```

...when you use the `obsidian://log` command.

**Comment by kontiainen** [comment]
Ahhh, now I get it. Tried formatting on the wrong settings field. Thank you!
