### ISSUE TITLE
Shortcuts on Android

### ISSUE THREAD

**Issue by scriptor-dga** [ryanjamurphy/lumberjack-obsidian#8]
How do I set up a shortcut like `obsidian://log` on Android?
If I add it to homescreen from Firefox, when I tap on it, it says "App isn't installed", but if I type it directly on the search bar in Firefox and go to "open in app", it works.

**Comment by mtalexan** [comment]
I use Tasker. I create a new Task and add a Browse URL action to it. Add the URL there, save it, add an Icon to the task, then back all the way out with the back button.

From your home screen, choose to add a shortcut from Tasker and it will let you pick a Tasker task by name.

**Comment by ryanjamurphy** [comment]
@scriptor-dga et al., let me know if @mtalexan's suggestion works for you and I'll close this issue. Thanks!

**Comment by mtalexan** [comment]
BTW, [here's](https://forum.obsidian.md/t/how-to-add-a-note-shortcut-to-the-homescreen-on-android/20889) the Obsidian Forum post on how to do the Advanced URI behavior to open a specific note. If you do the same things in Tasker or Automate, but use the `obsidian://log` as the URL instead, it will work.
